version: "3"

services:
  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - redis:/data
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    command: mongod
    volumes:
      - mongo:/data/db
  backend:
    build:
      dockerfile: dockerfiles/Dockerfile.api
      context: .
    ports:
      - 8080:8080
    links:
      - redis
      - mongo
      - starknet-devnet
    depends_on:
      starknet-devnet:
        condition: service_started
    restart: always
    environment:
      - CONFIG_PATH=/configs/config.yaml
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - ./abis:/app/abis
  indexer:
    build:
      dockerfile: dockerfiles/Dockerfile.indexer
      context: .
    ports:
      - 8081:8081
    links:
      - redis
      - mongo
      - starknet-devnet
    depends_on:
      starknet-devnet:
        condition: service_started
    restart: always
    environment:
      - CONFIG_PATH=/configs/config.yaml
      - MONGO_URI=mongodb://mongo:27017
      - NO_PROXY=true
    volumes:
      - ./abis:/app/abis
  starknet-devnet:
    image: shardlabs/starknet-devnet-rs:0.3.0
    command:
      - --seed=0
      - --port=5050
    volumes:
      - devnet:/data
    ports:
      - 5050:5050
  deployer:
    build:
      dockerfile: dockerfiles/Dockerfile.deploy_devnet
      context: .
    depends_on:
      starknet-devnet:
        condition: service_started
    restart: no
    volumes:
      - configs:/configs

volumes:
  redis:
  mongo:
  devnet:
  configs:
